# Generated by Django 4.2.11 on 2024-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Описание'),
        ),
    ]
